name: Deploy Next.js to GitHub Pages

on:
  push:
    branches:
      - main # Change this to your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.18.0' # Ensure this matches your required Node.js version

      - name: Install dependencies
        run: |
          npm install

      - name: Build
        run: |
          npm run build

      - name: Export and Deploy to GitHub Pages
        run: |
          npx next build && npx next export
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out # Default output directory for next export
          publish_branch: gh-pages # Branch to deploy to (usually gh-pages)
          cname: <your-custom-domain> # Optional: replace with your custom domain if you have one

